fn main() {
    let list_of_hashes = include_str!("whitelisted_wasms.txt")
        .lines()
        .filter_map(|line| line.split_once(' '))
        .map(|(hash, _comment)| format!("    \"{hash}\"",))
        .collect::<Vec<String>>();

    let hashes_count = list_of_hashes.len();
    let serialized_contents = list_of_hashes.join(",\n");

    let output = format!(
        r#"/// this files is generated by build.rs script
#[allow(clippy::all)]
pub const WHITELISTED_WASMS: [&str; {hashes_count}] = [
{serialized_contents},
];"#
    );

    std::fs::write("whitelisted_wasms.rs", output).expect("Failed to write output file.");
}
